# Generated by Django 4.0.4 on 2022-06-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playable', models.BooleanField(default=True)),
                ('image_uri', models.URLField()),
                ('cmc', models.IntegerField()),
                ('name', models.TextField()),
                ('oracle_id', models.UUIDField()),
                ('type_line', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('W', 'White'), ('U', 'Blue'), ('B', 'Black'), ('R', 'Red'), ('G', 'Green')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cube.archetype')),
                ('cards', models.ManyToManyField(blank=True, to='cube.card')),
                ('colors', models.ManyToManyField(to='cube.color')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='colors',
            field=models.ManyToManyField(blank=True, to='cube.color'),
        ),
        migrations.AddField(
            model_name='card',
            name='enabled_archetypes',
            field=models.ManyToManyField(blank=True, related_name='+', to='cube.archetype'),
        ),
        migrations.AddField(
            model_name='card',
            name='payed_off_archetypes',
            field=models.ManyToManyField(blank=True, related_name='+', to='cube.archetype'),
        ),
        migrations.AddField(
            model_name='archetype',
            name='enablers',
            field=models.ManyToManyField(blank=True, related_name='+', to='cube.card'),
        ),
        migrations.AddField(
            model_name='archetype',
            name='payoffs',
            field=models.ManyToManyField(blank=True, related_name='+', to='cube.card'),
        ),
    ]
